// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vffclsepbxtbaodwiduq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmZmNsc2VwYnh0YmFvZHdpZHVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMDQ3MjYsImV4cCI6MjA2ODc4MDcyNn0.r1dfS93UvXrdAU1nSgXNFvSXRu3D7KcGT3m9Ia0VoHI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});